In [ ]:
import requests
import pandas as pd

In [ ]:
base_url = "https://api.themoviedb.org/3/movie/top_rated?api_key=8568de5d499e38fd7cbf6ea5809d4b99&language=en-US&page="

In [ ]:
req = requests.get(base_url+"1")
req

In [ ]:
pd.DataFrame(req.json()["results"])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [ ]:
df = pd.DataFrame()

In [ ]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

In [ ]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,101.713,8.7,17555
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,98.110,8.7,23389
2,772071,Cuando Sea Joven,70-year-old Malena gets a second chance at lif...,2022-09-14,64.208,8.7,208
3,995133,"The Boy, the Mole, the Fox and the Horse","The unlikely friendship of a boy, a mole, a fo...",2022-12-25,35.916,8.6,245
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,62.665,8.6,10630
...,...,...,...,...,...,...,...
8555,15556,At First Sight,A blind man has an operation to regain his sig...,1999-01-15,8.308,6.0,200
8556,10433,Mad Dog and Glory,Wayne Dobie is a shy cop whose low-key demeano...,1993-03-05,15.817,6.0,304
8557,680028,Centigrade,A young American couple travel to the arctic m...,2020-08-28,12.184,6.0,229
8558,353569,Table 19,"Eloise, having been relieved of maid of honor ...",2017-03-03,8.574,6.0,871
8559,157351,The Truth About Emanuel,A troubled young woman becomes obsessed with h...,2014-01-10,7.415,6.0,215

In [ ]:
df.to_csv("movies_tmdb.csv")